"""
Constants related to Simple Pong game
"""

from src.models.pong import Color

# Constants
SCREEN_CAPTION = "Simple Pong"
SCREEN_WIDTH, SCREEN_HEIGHT = 210, 160
PADDLE_WIDTH, PADDLE_HEIGHT = SCREEN_WIDTH * 0.12, SCREEN_HEIGHT * 0.03
BALL_SIZE = int(SCREEN_WIDTH * 0.05)
WHITE: Color = (255, 255, 255)
BLACK: Color = (0, 0, 0)
FPS = 60
GAME_FONT_SIZE = 32
PADDLE_SPEED = SCREEN_WIDTH * 0.2
BALL_SPEEDS_X = [SCREEN_WIDTH * 0.05, SCREEN_WIDTH * 0.06, SCREEN_WIDTH * 0.07]
BALL_SPEEDS_Y = [SCREEN_WIDTH * 0.03, SCREEN_WIDTH * 0.04, SCREEN_WIDTH * 0.05]
PADDLE_HIT_REWARD = 2
BALL_FALLING_THROUGH_REWARD = -2
BALL_RESET_PROBABILITY_WHEN_HITTING_TOP_WALL = 1


FREQUENCY_FREQUENT = "frequent"
FREQUENCY_SPARSE = "sparse"

ARG_ENV_NAME = "env_name"

ENV_SIMPLE_PONG = "SimplePong"
ENV_COMPLEX_PONG = "ComplexPong"
