"""
Constants related to all Pong games
"""

from src.models.pong import Color

# Constants
SCREEN_CAPTION_SIMPLE_PONG = "Simple Pong"
SCREEN_CAPTION_COMPLEX_PONG = "Complex Pong"
SCREEN_WIDTH, SCREEN_HEIGHT = 210, 160
LARGE_PADDLE_WIDTH, PADDLE_HEIGHT = SCREEN_WIDTH * 0.12, SCREEN_HEIGHT * 0.03
SMALL_PADDLE_WIDTH = SCREEN_WIDTH * 0.06
BALL_SIZE = int(SCREEN_WIDTH * 0.05)
WHITE: Color = (255, 255, 255)
BLACK: Color = (0, 0, 0)
FPS = 60
GAME_FONT_SIZE = 32
PADDLE_SPEED = SCREEN_WIDTH * 0.2
BALL_SPEEDS_X = [SCREEN_WIDTH * 0.05, SCREEN_WIDTH * 0.06, SCREEN_WIDTH * 0.07]
BALL_SPEEDS_Y = [SCREEN_WIDTH * 0.03, SCREEN_WIDTH * 0.04, SCREEN_WIDTH * 0.05]
OBSTACLE_SPEED = SCREEN_WIDTH * 0.03
PADDLE_HIT_REWARD = 2
BALL_FALLING_THROUGH_REWARD = -2
BALL_RESET_PROBABILITY_WHEN_HITTING_TOP_WALL = 1


FREQUENCY_FREQUENT = "frequent"
FREQUENCY_SPARSE = "sparse"

ARG_ENV_NAME = "env_name"

ENV_SIMPLE_PONG = "SimplePong"
ENV_COMPLEX_PONG = "ComplexPong"


SIMPLE_PONG_ACTION_PADDLE_LEFT = 0
SIMPLE_PONG_ACTION_PADDLE_STAY = 1
SIMPLE_PONG_ACTION_PADDLE_RIGHT = 2


COMPLEX_PONG_ACTION_PADDLE1_LEFT_PADDLE2_LEFT = 0
COMPLEX_PONG_ACTION_PADDLE1_STAY_PADDLE2_LEFT = 1
COMPLEX_PONG_ACTION_PADDLE1_RIGHT_PADDLE2_LEFT = 2
COMPLEX_PONG_ACTION_PADDLE1_LEFT_PADDLE2_STAY = 3
COMPLEX_PONG_ACTION_PADDLE1_STAY_PADDLE2_STAY = 4
COMPLEX_PONG_ACTION_PADDLE1_RIGHT_PADDLE2_STAY = 5
COMPLEX_PONG_ACTION_PADDLE1_LEFT_PADDLE2_RIGHT = 6
COMPLEX_PONG_ACTION_PADDLE1_STAY_PADDLE2_RIGHT = 7
COMPLEX_PONG_ACTION_PADDLE1_RIGHT_PADDLE2_RIGHT = 8

OBSTACLE_SIDE_TOP = "top"
OBSTACLE_SIDE_BOTTOM = "bottom"
OBSTACLE_SIDE_LEFT = "left"
OBSTACLE_SIDE_RIGHT = "right"
